SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  # Ubuntu 26.04 LTS: latest stable Ubuntu release
  config.vm.box = "bento/ubuntu-26.04"

  config.vm.define "yowazgaS" do |server|
    server.vm.hostname = "yowazgaS"

    server.vm.network "private_network",
      ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.name = "yowazgaS"
      vb.memory = 2048
      vb.cpus = 1
    end

    server.vm.provision "shell",
      path: "scripts/server.sh",
      args: [SERVER_IP]
  end
end
