SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  # Ubuntu 26.04 LTS: latest stable Ubuntu release
  config.vm.box = "bento/ubuntu-26.04"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "yowazgaS", primary: true do |server|
    server.vm.hostname = "yowazgaS"

    server.vm.network "private_network",
      ip: SERVER_IP

    server.vm.provider "virtualbox" do |vb|
      vb.name = "yowazgaS"
    end

    server.vm.provision "shell",
      path: "scripts/server.sh",
      args: [SERVER_IP]
  end

  config.vm.define "yowazgaSW" do |worker|
    worker.vm.hostname = "yowazgaSW"

    worker.vm.network "private_network",
      ip: WORKER_IP

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "yowazgaSW"
    end

    worker.vm.provision "shell",
      path: "scripts/worker.sh",
      args: [SERVER_IP, WORKER_IP]
  end
end
